---
title: "금융통계학2"
output: html_document
---

## 1. R 시작

### 1.1 R기초문법

#### 1.1.1 Vector
* Creating vector
* Useful functions to create vectors
* Slicing vector I
* Length of vector   
* Operation on vector
* Logical operation
* Slicing vector II
* %in%, match() function

#### 1.1.2 Matrix
* Create matrix
* Matrix function   
* column bind and row bind

#### 1.1.3 Dataframe
* Selecting the elements
* cbind/rbind

### 1.2 통계 함수

#### 1.2.1 기초통계량      
* summary
* min,max,sum,mean
* exp,log
* indexing data frame 
* 데이터 평균값으로 대체

#### 1.2.2 for문 
* 간단한 for문 만들기
* 반복작업을 단순화
* 잘못된 for문 사용

#### 1.2.3 function 
* 지역변수/전역변수/매개변수의 개념
* 간단한 함수 만들기

#### 1.2.4 if문   
* 예제를 통한 if문 사용
* ifelse 활용하기

### 1.3 문자열 처리

#### 1.3.1 paste를 활용하여 문자열 합치기

#### 1.3.2 문자열 추출
* grep, grepl, regexpr
* nchar를 이용한 문자열의 갯수 확인
* substr을 활용하여 문자열의 특정부분 추출

#### 1.3.3 문자열 분리하기
* strsplit을 활용하여 문자열 분리

#### 1.3.4 문자 위치 찾기
* regexpr, gregexpr 활용
* gsub을 활용하여 문자 위치를 찾아 바꾸기

#### 1.3.5 정규표현식
* 정규표현식이란?
* 문자 분리하기
* 정규표현식으로 문자열 찾기
* 정규표현식 예제

#### 1.3.6 stringr package
* 패키지 함수를 이용한 문자열 처리




## 2. 데이터 처리

### 2.1. 데이터 import

#### 2.1.1 readr을 활용하여 csv, excel 파일 읽기

#### 2.1.2 readxl 패키지를 통해 엑셀의 sheet이름 확인

### 2.2. 데이터 다루기

#### 2.2.1 데이터프레임의 다른 형태 tibble

#### 2.2.2 Tidy를 활용하여 데이터 분석전 데이터 클렌징
* column조작하기
* 데이터 형태 변경
* _join()함수를 활용하여 데이터 합치기

### 2.3 탐색적 데이터 분석 

#### 2.3.1 rvest를 활용하여 데이터 분석하기
* rvest 함수 활용
* 예제를 통한 학습

#### 2.3.2 dplyr를 활용하여 데이터 분석하기
* dplyr 함수 활용
* 예제를 통한 학습




## 3. 데이터시각화

### 3.1 plot의 기본

#### 3.1.1 plotting point

#### 3.1.2 add lines and points

#### 3.1.3 par()

### 3.2 ggplot2

#### 3.2.1 ggplot 기본

#### 3.2.2 histogram

#### 3.2.3 boxplot

#### 3.2.4 ggplot 예제




## 4. Model 

### 4.1 단순회귀분석 (출처: R을 활용한 선형 회귀 분석 지은이: 강근석, 유한조)

#### 4.1.1 회귀분석의 기초 개념

#### 4.1.2 단순선형 회귀모형

#### 4.1.3 회귀계수의 추정

#### 4.1.4 회귀직선의 적합도와 분산분석

#### 4.1.5 단순회귀 분석에서의 추론

### 4.2 회귀모형의 진단과 수정

#### 4.2.1 부분 F검정

#### 4.2.2 변수변환

#### 4.2.3 표준화 회귀계수

#### 4.2.4 다중공선성의 탐색




## 5. 크롤링 
#### (출처: R과 Java로 크롤링하자 지은이: 노규성,김진희,박성태,김근원, 김도연)

### 5.1 크롤링이란?

### 5.2 네이버 뉴스 크롤링하기

#### 5.2.1 url 정리하기

#### 5.2.2 url 연결하기

#### 5.2.3 네이버 뉴스 기사 제목 크롤링

#### 5.2.4 text로 글 정제하기

#### 5.2.5 for문을 활용하여 년도월별 추출

### 5.3 네이버 블로그 크롤링하기   

#### 5.3.1 api활용

#### 5.3.2 네이버 블로그 내용 크롤링

#### 5.3.3 text로 글 정제하기




## 6. 문서화 

### 6.1 Rmarkdown이란?

### 6.2 Rmarkdown의 시작

#### 6.2.1 주석 입력하기 

#### 6.2.2 표만들기

#### 6.2.3 그림 넣기




