---
title: "Regression example"
author: "hyo"
date: '2020 5 25 '
output: html_document
---
---
title: "Regression_example"
author: "hyo"
date: '2020 5 25 '
output: html_document
---

### 문제1 
#### 라이브러리 regbook 안에 있는 aflength 데이터를 사용하여 회귀분석을 시행하여라
  + `install.packages("devtools");library(devtools);install_github("regbook/regbook")` 실행 후 데이터 사용


##### 1) 데이터를 head()를 사용하여 확인하고 종속변수를 foot, 설명변수를 forearm으로 하여 산점도를 확인해보고 대략적인 상관관계를 설명하시오


##### 2) 위의 두 변수간의 상관관계를 수치로 구하고 두변수간의 관계를 설명하시오

#### 3) 단순 회귀 분석을 시행하시오
  + plot 및 분석 결과 설명 

### 문제2 
#### 중고차 가격자료 `usedcars`에 대한 회귀분석에서 가격(price)에 대해
  + 1) 각 회귀계수가 0이라는 가설에 대한 t검정을 하여라
  + 2) 각 회귀계수에 대한 95% 신뢰구간을 구하여라
속변수와 독립변수간의 유의한 상관관계가 있다고 말 할 수 있지만 CC변수는 귀무가설을 기각하지 못한다


### 문제3 
#### 위 데이터에 대한 회귀분석 문제에서 Y의 평균에 대한 신뢰구간과 새로운 Y값에 대한 예측구간을 다음 경우에 대해 각각 구해보자
  + year = 60, mileage = 100000, cc = 2000, automatic = 1


### 문제4 
#### 자료 'hald'는 1932년 미국 화학공학 학회지에 발표된것으로, 시멘트가 굳을때 발생하는 열량에 시멘트의 네가지 성분들이 미치는 영향을 분석한 것이다. `data(hald)`를 사용하여 y에 대해 x변수들의 다중공선성의 유무를 판단하시오


### 문제5 
#### 위 데이터를 dplyr를 활용하여 회귀분석을 시행하시오
  + 힌트 : do(reg=lm(Y~X1+X2+X3,data=.))를 통해 회귀식을 구성한다
